name: preprocess_videos
channels:
 - conda-forge
 - nvidia
 - defaults
dependencies:
 - python=3.12
 - numpy=2.2.2
 - h5py=3.12.1
 - imageio=2.37.0
 - tifffile=2025.1.10
 - pynrrd=1.1.3
 - tqdm=4.67.1
 - scipy=1.15.1
 - pillow=11.1.0
 - pip
 - pip:
   - jax[cuda]==0.5.0
   - jaxlib==0.5.0
   - nd2reader==3.3.1
   - pims==0.7
   - slicerator==1.1.0